---
- name: Restart analytics postgresql
  ansible.builtin.service:
    name: postgresql
    state: restarted

- name: Reload analytics postgresql
  ansible.builtin.service:
    name: postgresql
    state: reloaded

- name: Restart analytics pgbouncer
  ansible.builtin.service:
    name: pgbouncer
    state: restarted
