module "region" {
  source = "../../modules/region"

  project_tag               = var.project_tag
  environment               = "us"
  region_code               = var.region_code
  existing_vpc_id           = var.existing_vpc_id
  existing_vpc_cidr         = var.existing_vpc_cidr
  ssh_keys                  = var.ssh_keys
  admin_ipv4_cidrs          = var.admin_ipv4_cidrs
  web_ipv4_cidrs            = var.web_ipv4_cidrs
  db_access_ipv4_cidrs      = var.db_access_ipv4_cidrs
  backend_count             = var.backend_count
  worker_count              = var.worker_count
  compute_resource_type     = var.compute_resource_type
  backend_plan              = var.backend_plan
  web_portal_enabled        = var.web_portal_enabled
  web_portal_plan           = var.web_portal_plan
  bare_metal_mdisk_mode     = var.bare_metal_mdisk_mode
  coordinator_plan          = var.coordinator_plan
  worker_plan               = var.worker_plan
  os_id                     = var.os_id
  enable_ipv6               = var.enable_ipv6
  app_port                  = var.app_port
  postgres_version          = var.postgres_version
  citus_package             = var.citus_package
  postgres_admin_password   = var.postgres_admin_password
  app_db_name               = var.app_db_name
  app_db_user               = var.app_db_user
  app_db_password           = var.app_db_password
  remote_analytics_base_url = var.remote_analytics_base_url
  tags                      = var.tags
}
